import type { NextPage } from "next";
import React,{useState} from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBars ,faXmark} from '@fortawesome/free-solid-svg-icons'
const Home: NextPage = () => {
  const [nav,setNav]=useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <nav>
          <div className="flex px-4 py-2 justify-between">
            <img className="w-14" src="https://project03-navbar.vercel.app/logo.png" alt="" />
          <div className="py-3" onClick={()=>setNav(!nav)}>
            
          
            {nav?<FontAwesomeIcon icon={faXmark} className='w-4'/>:<FontAwesomeIcon icon={faBars} className='w-5'/>}
          </div>
            
          </div>
          <ul className={!nav?"hidden":'px-6 py-4 shadow-[1px_5px_27px_0px_rgba(0,0,0,0.75)] space-y-4'}>
            <li>About</li>
            <li>How it Works</li>
            <li>Crypto</li>
            <li>Explore Marketplace</li>
            <li>Marketplace</li>
          <div className="px-8 flex justify-between">
            
            <button className="font-[500]  px-3 py-2">Sign In</button>
            <button className="font-[500] bg-black px-6 py-2 rounded text-white">Get Started</button>
          </div>
          </ul>
        </nav>
        {/* <nav>
          <ul>
            <li><img className="w-10" src="https://project03-navbar.vercel.app/logo.png" alt="" /></li>
            <li>How it Works</li>
            <li>Crypto</li>
            <li>Marketplace</li>
            <li>Sign In</li>
            <li className="px-4 py-2 bg-black">Get Started</li>
          </ul>
        </nav> */}
      </section>
    </div>
  );
};

export default Home;
