import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faLocationPin,faMailBulk,faStore,faPerson } from '@fortawesome/free-solid-svg-icons'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <section className="flex justify-around py-4 bg-purple-800 text-white">
      <div className="">
        <span className="flex gap-2 items-center"><FontAwesomeIcon className="text-white w-3" icon={faPerson}/><h1>info@example.com</h1></span>
      </div>
      <div className="flex gap-4">
        <span className="flex gap-2 items-center"><FontAwesomeIcon className="text-white w-3" icon={faLocationPin}/><h1>Branches</h1></span>
        <span className="flex gap-2 items-center"><FontAwesomeIcon className="text-white w-4" icon={faMailBulk}/><h1>Stores</h1></span>
        <span className="flex gap-2 items-center"><FontAwesomeIcon className="text-white w-4" icon={faStore}/><h1>Contact us</h1></span>
      </div>
    </section>
    </div>
  );
};

export default Home;
